def test_that_fails():
    raise ValueError()
